<?php

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;

/**
 * Implements hook_theme().
 */
function blender_theme($existing, $type, $theme, $path) {
  $variables = array(
    'blender' => array(
      'variables' => array(
        'articles' => NULL,
        'journals' => NULL,
        'journalfilter' => 0,
        'more' => NULL,
        'page' => 'inbox',
        'inbox_new' => 0,
        'recommend_new' => 0,
      ),
      'template' => 'blender',
    ),
    'blender-article' => array(
      'variables' => array(
        'articles' => NULL,
      ),
      'template' => 'blender-article',
    ),
    'blender-comment' => array(
      'variables' => array(
        'comments' => NULL,
      ),
      'template' => 'blender-comment',
    ),
  );
  return $variables;
}

/**
 * Implements hook_cron().
 */
function blender_cron() {

  $queue = \Drupal::queue('journal_fetcher');

  if($queue->numberOfItems() > 0)
  {
    \Drupal::logger('blender')->notice("Not queuing more journals; queue not empty.");
  }
  else
  {

    $storage = \Drupal::entityTypeManager()->getStorage('blender_journal');
    $jids = \Drupal::entityQuery('blender_journal')
      ->condition('active', TRUE)
      ->condition('last_update',\Drupal::time()->getRequestTime()-(24*60*60),'<')
      ->execute();

    $journals = $storage->loadMultiple($jids);


    foreach( $journals as $j ) {
      if($queue->createItem($j))
      {
        \Drupal::logger('blender')->notice("Queued ".$j->abbr->value);
      }
    }
  }

  //purge articles more than 180 days old that are not starred or preserved
  $a_ids = \Drupal::entityQuery('blender_article')
    ->condition('is_starred',0)
    ->condition('date_added',\Drupal::time()->getRequestTime()-(24*60*60*180),'<')
    ->condition('preserve',0)
    ->execute();


  $articles = \Drupal::entityTypeManager()->getStorage('blender_article')->loadMultiple($a_ids);
  foreach($articles as $a)
    $a->delete();

  \Drupal::logger('blender')->notice("Deleted ".count($a_ids)." old articles.");

  //if slack aggregation is enabled; seek comments and votes made since last cron run
  $config = \Drupal::config('blender-slack.settings');
  if($config->get('blender-slack.enabled') && $config->get('blender-slack.aggregate'))
  {

    $last_cron = \Drupal::state()->get('system.cron_last');

    $attachments = [];

    //first, comments
    $list = \Drupal::entityTypeManager()->getStorage('blender_comment')->getAggregateQuery()
      ->condition('timestamp',$last_cron,'>=')
      ->aggregate('article_id','count')
      ->groupBy('article_id')->execute();

    foreach($list as $a)
    {
      $c_ids = \Drupal::entityQuery('blender_comment')
        ->condition('article_id',$a['article_id'])
        ->condition('timestamp',$last_cron,'>=')
        ->sort('timestamp','ASC')->execute();

      $comments = \Drupal::entityTypeManager()->getStorage('blender_comment')->loadMultiple($c_ids);

      $this_article = \Drupal::entityTypeManager()->getStorage('blender_article')->load($a['article_id']);

      $commenters = [];
      $comment_text = '';

      foreach($comments as $c)
      {
        $name = $c->get('user_id')->entity->getDisplayName();
        if(!in_array($name,$commenters,true))
          $commenters[] = $name;

        $comment_text .= '*'.$name.':* '.html_entity_decode(strip_tags($c->get('text')->value), ENT_QUOTES|ENT_HTML5);
      }

      $pt_string = array_shift($commenters);
      while(count($commenters) > 0)
      {
        if(count($commenters) > 1)
          $pt_string.= ', '.array_shift($commenters);
        else
          $pt_string.= ' and '.array_shift($commenters);
      }
      $pt_string.= ' commented on an article in '.$this_article->get('journal_id')->entity->get('abbr')->value.'.';

      $attachments[] =
      [
        'pretext' => $pt_string,
        'title' => $this_article->get('title')->value,
        'text' => $comment_text,
        'color' => 'good',
        "actions" => [
          [
            "type" => "button",
            "text" => "View Abstract",
            "url" => 'http://dx.doi.org/'.$this_article->get('doi')->value,
          ],
          [
            "type" => "button",
            "text" => "Open in Blender",
            "url" => \Drupal\Core\Url::fromRoute('blender.blender_article.canonical',[ 'blender_article' => $this_article->get('id')->value, ],[ 'absolute' => true, ])->toString(),
          ],
        ],
      ];
    }

    //now, votes
    $list = \Drupal::entityTypeManager()->getStorage('blender_vote')->getAggregateQuery()
      ->condition('timestamp',$last_cron,'>=')
      ->aggregate('article_id','count')
      ->groupBy('article_id')->execute();

    foreach($list as $a)
    {
      $v_ids = \Drupal::entityQuery('blender_vote')
        ->condition('article_id',$a['article_id'])
        ->condition('timestamp',$last_cron,'>=')
        ->sort('timestamp','ASC')->execute();

      $votes = \Drupal::entityTypeManager()->getStorage('blender_vote')->loadMultiple($v_ids);

      $this_article = \Drupal::entityTypeManager()->getStorage('blender_article')->load($a['article_id']);

      $voters = [];
      foreach($votes as $v)
      {
        $name = $v->get('user_id')->entity->getDisplayName();
        if(!in_array($name,$voters))
          $voters[] = $name;
      }

      $pt_string = array_shift($voters);
      while(count($voters)>0)
      {
        if(count($voters) > 1)
          $pt_string.= ', '.array_shift($voters);
        else
          $pt_string.= ' and '.array_shift($voters);
      }
      $pt_string.= ' voted for an article in '.$this_article->get('journal_id')->entity->get('abbr')->value.'.';

      $vc = \Drupal::entityQuery('blender_vote')
        ->condition('article_id',$this_article->get('id')->value)
        ->count()->execute();

      $attachments[] =
      [
        'pretext' => $pt_string,
        'title' => $this_article->get('title')->value,
        'text' => "Total votes: ".$vc,
        'color' => '#ce0610',
        "actions" => [
          [
            "type" => "button",
            "text" => "View Abstract",
            "url" => 'http://dx.doi.org/'.$this_article->get('doi')->value,
          ],
          [
            "type" => "button",
            "text" => "Open in Blender",
            "url" => \Drupal\Core\Url::fromRoute('blender.blender_article.canonical',[ 'blender_article' => $this_article->get('id')->value, ],[ 'absolute' => true, ])->toString(),
          ],
        ],

      ];
    }

    //post to Slack, but keep number of attachments per post to 20
    $slack['channel'] = $config->get('blender-slack.channel');
    $offset = 0;
    $chunk_size = 20;
    $url = 'https://slack.com/api/chat.postMessage';
    $headers['Content-type'] = 'application/json';
    $headers['Authorization'] = 'Bearer '.$config->get('blender-slack.workspace-token');

    while($offset < count($attachments))
    {
      $att = array_slice($attachments,$offset,$chunk_size);
      $offset += $chunk_size;

      $slack['attachments'] = $att;
      $response = \Drupal::httpClient()->request('POST',$url, [
        'headers' => $headers,
        'body' => json_encode($slack)
      ]);

      if($response->getStatusCode() != 200)
      {
        \Drupal::logger('blender')->warning("Received error code ".$response->getStatusCode()," when posting comments and votes to Slack (url = ".$url.").");
        break;
      }
    }
  }


  //see if any articles have been starred within the last week
  $ts_res = \Drupal::entityQuery('blender_article')
    ->condition('is_starred',1)
    ->condition('star_date',\Drupal::time()->getRequestTime()-(24*60*60*7),'>')
    ->count()->execute();

  //if no articles have been starred in the past week, it's time to look for new ones to star.
  //query votes table; filter by article.is_starred=false and #votes > 1, aggregate on count, sort descending
  if($ts_res == 0)
  {
    \Drupal::logger('blender')->notice("Looking for potential articles to star.");
    $candidates = \Drupal::entityTypeManager()->getStorage('blender_vote')->getAggregateQuery()
      ->aggregate('article_id','count')
      ->condition('article_id.entity:blender_article.is_starred',0)
      ->conditionAggregate('article_id','COUNT',1,'>')
      ->groupBy('article_id')
      ->sortAggregate('article_id','count','DESC')
      ->range(0,2)->execute();


    \Drupal::logger('blender')->notice("Found ".count($candidates)." articles to star.");

    if(count($candidates) > 0)
    {
      $slack = [];
      $offset = 0;
      $timestamp = \Drupal::time()->getRequestTime();
      foreach($candidates as $c)
      {

        //Debugging statements
//         $str = "";
//         foreach($c as $key=>$value)
//           $str .= ' '.$key.': '.$value.', ';
//         \Drupal::logger('blender')->notice($str);

        $a = \Drupal::entityTypeManager()->getStorage('blender_article')->load($c['article_id']);
        $a->set('is_starred',true);
        $a->set('star_date',$timestamp+$offset);
        $a->set('preserve',true);
        $a->save();

        $slack['attachments'][] = [
          "title" => $a->get('title')->value,
          "color" => "#FFAF1D",
          "fields" => [
            [
              "title" => "Assigned to",
              "value" => $a->get('user_id')->entity->getDisplayName(),
              "short" => true,
            ],
            [
              "title" => "Journal",
              "value" => $a->get('journal_id')->entity->get('abbr')->value,
              "short" => true,
            ],
            [
              "title" => "Total Votes",
              "value" => $c['article_id_count'],
              "short" => true,
            ],
          ],
          "actions" => [
            [
              "type" => "button",
              "text" => "View Abstract",
              "url" => 'http://dx.doi.org/'.$a->get('doi')->value,
            ],
            [
              "type" => "button",
              "text" => "Open in Blender",
              "url" => \Drupal\Core\Url::fromRoute('blender.blender_article.canonical',[ 'blender_article' => $a->get('id')->value, ],[ 'absolute' => true, ])->toString(),
            ],
          ],
        ];

        $offset++;
      }

      //post to slack
      if($config->get('blender-slack.enabled'))
      {
        $slack['channel'] = $config->get('blender-slack.channel');
        $txt = 'The following article';
        if(count($candidates) > 1)
          $txt.= 's have ';
        else
          $txt.= ' has ';
        $txt.='been selected for discussion at the next group meeting.';
        $slack['text'] = $txt;

        $url = 'https://slack.com/api/chat.postMessage';
        $headers['Content-type'] = 'application/json';
        $headers['Authorization'] = 'Bearer '.$config->get('blender-slack.workspace-token');

        $response = \Drupal::httpClient()->request('POST',$url, [
          'headers' => $headers,
          'body' => json_encode($slack)
        ]);

        if($response->getStatusCode() != 200)
        {
          \Drupal::logger('blender')->warning("Received error code ".$response->getStatusCode()," when posting starred articles to Slack (url = ".$url.").");
        }
      }

    }
  }

}

/**
* Implements hook_entity_base_field_info().
*/
function blender_entity_base_field_info(EntityTypeInterface $entity_type)
{
  if($entity_type->id() === 'user') {
    $fields['slack_id'] = BaseFieldDefinition::create('string')
      ->setLabel(t('Slack ID'))
      ->setDescription(t('Slack ID for this user (e.g., U0XAXAA8L)'))
      ->setRevisionable(TRUE)
      ->setSettings( array (
        'default_value' => '',
        'max_length' => 9
      ))
      ->setDisplayOptions('view', array( 'type' => 'string', 'weight' => -6 ))
      ->setDisplayOptions('form', array( 'type' => 'string_text_field', 'weight' => -6))
      ->setDisplayConfigurable('form',TRUE)
      ->setDisplayConfigurable('view',TRUE);

    return $fields;
  }

}



