blender-slack.settings:
  type: config_object
  label: 'Blender Slack Integration Settings'
  mapping:
    enabled:
      type: boolean
      label: 'Enable Slack Integration'
    workspace-token:
      type: string
      label: 'OAuth Token for Slack Workspace'
    bot-token:
      type: string
      label: 'OAuth Token for Bot User in Slack'
    channel:
      type: string
      label: 'Channel ID where Slack messages are posted.'
